---
title: Darcy
timezone: UTC
collections:
  floorplans:
    title: Floorplans
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: me@williamvuong.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: 
url: https://williamvuong.com/darcy
twitter_username: william___vuong
github_username: wnvuong
markdown: kramdown
